version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: queries_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: queries
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - queries_db
    depends_on: 
      - queries_db

volumes:
  pgdata:
    driver: local